CI: Pin all GitHub Actions to full-length commit hashes
PumasAI/ProvenanceBase.jl pull request #11
Opened 2024-07-01 23:47 UTC by DilumAluthge

2024-07-02 07:37 UTC, MichaelHatherly requested changes

2024-07-02 07:37 UTC, MichaelHatherly commented on .github/workflows/CI.yml
>        - uses: julia-actions/julia-runtest@v1
Not changed to the hash version.

2024-09-17 13:00 UTC, andreasnoack commented on .github/workflows/CI.yml
>        - uses: julia-actions/julia-runtest@v1
```suggestion
      - uses: julia-actions/julia-runtest@d0c4f093badade621cd041bba567d1e832480ac2 # 1.10.0
```

2024-09-26 06:42 UTC, andreasnoack approved these changes

2024-09-26 06:42 UTC, merged